#!/bin/bash
# Centralized version pins for external dependencies.

if [ -n "${FRANKLIN_VERSIONS_LOADED:-}" ]; then
  return 0 2>/dev/null || true
fi

FRANKLIN_NVM_VERSION="${FRANKLIN_NVM_VERSION:-v0.40.3}"
FRANKLIN_NVM_INSTALL_SHA256="${FRANKLIN_NVM_INSTALL_SHA256:-2d8359a64a3cb07c02389ad88ceecd43f2fa469c06104f92f98df5b6f315275f}"
FRANKLIN_ANTIGEN_VERSION="${FRANKLIN_ANTIGEN_VERSION:-v2.2.3}"
FRANKLIN_ANTIGEN_URL="${FRANKLIN_ANTIGEN_URL:-https://raw.githubusercontent.com/zsh-users/antigen/${FRANKLIN_ANTIGEN_VERSION}/antigen.zsh}"

FRANKLIN_VERSIONS_LOADED=1

export FRANKLIN_NVM_VERSION FRANKLIN_NVM_INSTALL_SHA256 FRANKLIN_ANTIGEN_VERSION FRANKLIN_ANTIGEN_URL FRANKLIN_VERSIONS_LOADED
